# Our specific tasks for configuring nginx
# Most is done by the imported geerlingguy.nginx role

- name: certbot | Install deps
  become: yes
  apt:
    name: ['software-properties-common', 'python3-apt']
    state: present
  when: inventory == 'cloud'

- name: certbot | Install ppa
  become: yes
  apt_repository:
    repo: ppa:certbot/certbot
    state: present
  when: inventory == 'cloud'

- name: certbot | Install packages
  become: yes
  apt:
    name: 'python-certbot-nginx'
    state: present
  when: inventory == 'cloud'

- name: nginx | Copy SSL certificate
  copy:
    src: weblab.crt
    dest: "{{ ssl_certificate_folder }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx
  when: inventory == 'production'

- name: nginx | Copy SSL private key
  copy:
    src: weblab.key
    dest: "{{ ssl_key_folder }}"
    owner: root
    group: ssl-cert
    mode: 0640
  notify:
    - reload nginx
  when: inventory == 'production'

- name: nginx | Copy DH params
  copy:
    src: dhparams.pem
    dest: "{{ dh_param_path }}"
    owner: root
    group: root
    mode: 0640
  notify:
    - reload nginx
  when: inventory == 'production'

- name: nginx | Configure nginx
  become: yes
  import_role:
    name: geerlingguy.nginx

- name: nginx | Open http(s) ports
  ufw:
    name: Nginx Full
    rule: allow
    state: enabled

- name: certbot | Configure nginx
  become: yes
  shell: 'certbot --non-interactive --nginx --agree-tos --email {{ certbot_email }} --no-eff-email
    --keep-until-expiring
    --domains {{ webserver_fqdn.split(" ") | join(",") }}'
  register: certbot_result
  when: inventory == 'cloud'
  changed_when: '"Keeping" not in certbot_result.stdout'
