# Our specific tasks for configuring nginx
# Most is done by our dependent role

- name: nginx | Include Django config
  include_vars: roles/django/vars/main.yml

- name: nginx | Copy SSL certificate
  copy:
    src: weblab.crt
    dest: "{{ ssl_certificate_folder }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx

- name: nginx | Copy SSL private key
  copy:
    src: weblab.key
    dest: "{{ ssl_key_folder }}"
    owner: root
    group: ssl-cert
    mode: 0640
  notify:
    - reload nginx

- name: nginx | Configure nginx
  import_role:
    name: geerlingguy.nginx

- name: nginx | Open https port
  ufw:
    name: Nginx Full
    rule: allow
    state: enabled
