# Our specific tasks for configuring nginx
# Most is done by the imported geerlingguy.nginx role

- name: Certbot | Install deps
  become: true
  apt:
    name: ["software-properties-common", "python3-apt"]
    state: present
  when: inventory == 'cloud'

- name: Certbot | Install ppa
  become: true
  apt_repository:
    repo: ppa:certbot/certbot
    state: present
  when: inventory == 'cloud'

- name: Certbot | Install packages
  become: true
  apt:
    name: "python-certbot-nginx"
    state: present
  when: inventory == 'cloud'

- name: Nginx | Copy SSL certificate
  copy:
    src: weblab.crt
    dest: "{{ ssl_certificate_folder }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx
  when: inventory == 'production'

- name: Nginx | Copy SSL private key
  copy:
    src: weblab.key
    dest: "{{ ssl_key_folder }}"
    owner: root
    group: ssl-cert
    mode: 0640
  notify:
    - reload nginx
  when: inventory == 'production'

- name: Nginx | Copy DH params
  copy:
    src: dhparams.pem
    dest: "{{ dh_param_path }}"
    owner: root
    group: root
    mode: 0640
  notify:
    - reload nginx
  when: inventory == 'production'

- name: Nginx | Configure nginx
  become: true
  import_role:
    name: geerlingguy.nginx

- name: Nginx | Open http(s) ports
  ufw:
    name: Nginx Full
    rule: allow
    state: enabled

- name: Certbot | Configure nginx
  become: true
  shell:
    'certbot --non-interactive --nginx --agree-tos --email {{ certbot_email }}
    --no-eff-email --keep-until-expiring --domains {{ webserver_fqdn.split(" ")
    | join(",") }}'
  register: certbot_result
  when: inventory == 'cloud'
  changed_when: '"Keeping" not in certbot_result.stdout'
