# Restart Celery when we've changed its configuration in any way

- name: reload systemd
  become: true
  systemd: daemon_reload=yes

- name: clean celery state
  become: true
  file:
    path: '{{ item.path }}'
    state: absent
  with_items: '{{ celery_state_files.files }}'

- name: restart celery
  listen: restart experiment runner
  become: true
  service:
    name: '{{ celery_service_name }}'
    state: restarted
