# Configure geerlingguy.nginx

nginx_remove_default_vhost: yes
# nginx_extra_http_options: |
#   proxy_buffering    off;
#   proxy_set_header   X-Real-IP $remote_addr;
#   proxy_set_header   X-Scheme $scheme;
#   proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
#   proxy_set_header   Host $http_host;

nginx_vhosts:
  # Our main host configuration
  - listen: "{{ (inventory == 'dev') | ternary('80', '443 ssl http2') }}"
    server_name: "{{ webserver_fqdn }}"
    filename: "{{ webserver_fqdn }}.conf"
    template: "{{ nginx_vhost_template }}"
    state: "present"
    extra_parameters: |
      {% if inventory != 'dev' %}
      ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA:ECDHE-ECDSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA256:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';
      ssl_prefer_server_ciphers on;
      ssl_dhparam {{ dh_param_path }}

      ssl_certificate     {{ ssl_certificate }};
      ssl_certificate_key {{ ssl_certificate_key }};
      {% endif %}
      charset     utf-8;

      location /media  {
        alias {{ django_media_path }};
      }

      location /static {
        alias {{ django_staticfiles_path }};
      }

      # Deny illegal Host headers
      if ($host !~* ^({{ webserver_fqdn }})$ ) {
        return 444;
      }

      # Finally, send all non-static requests to the Django server.
      location / {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect   off;
        proxy_buffering  off;  # Don't buffer responses from Django

        uwsgi_pass  unix://{{ uwsgi_socket }};
        include     /etc/nginx/uwsgi_params;
      }

  # Redirect non-https traffic to https
  - listen: "80"
    server_name: "{{ webserver_fqdn }}"
    return: "301 https://$host$request_uri"
    filename: "{{ webserver_fqdn }}.80.conf"
    state: "{{ (inventory == 'dev') | ternary('absent', 'present') }}"
