# Playbook for setting up the Celery task queue server & web service for experiment running

- hosts: task_queue
  roles:
    - python
    - celery

- hosts: task_queue
  become: yes
  roles:
    - fc-web-service
