# Playbook for setting up the Celery task queue server & web service for experiment running

- hosts: task_queue
  roles:
    - core
    - git
    - python
    - celery
    - { role: fc-web-service, become: yes }
