# Playbook for setting up the Django front-end to the Web Lab

- hosts: webserver
  roles:
    - core
    - git
    - python
    - django
    - { role: uwsgi, become: yes }
    - { role: nginx, become: yes }
