# Variables for this role

# Where Django files are located

django_checkout: "{{ django_dir }}/WebLab"
django_app_path: "{{ django_checkout }}/weblab"
django_static_path: "{{ django_app_path }}/static"
django_data_path: "{{ django_dir }}/data"
django_staticfiles_path: "{{ django_data_path }}/staticfiles"
django_media_path: "{{ django_data_path }}/media"
django_entity_repos_path: "{{ django_data_path }}/repositories"
django_virtualenv: "{{ django_dir }}/venv"

# Database settings

postgresql_databases:
  - name: "{{ django_db_name }}"
    lc_collate: 'en_GB.UTF-8'
    lc_ctype: 'en_GB.UTF-8'
    #owner: "{{ django_db_user }}"
postgresql_users:
  - name: "{{ django_db_user }}"
    password: "{{ django_db_pass }}"
    priv: ALL
    db: "{{ django_db_name }}"
    # role_attr_flags: CREATEDB iff inventory==dev
    # Can't do this here; need to use a task and when:
postgresql_locales:
  - 'en_GB.UTF-8'
