---
# This step is a workaround for the next step below which fails because
# it tries to add a key from an hkp:// address instead of an hkps:// 
- name: Add PPA for Nginx manually.
  command: add-apt-repository -y ppa:nginx/{{ nginx_ppa_version }}
  when: nginx_ppa_use

- name: Add PPA for Nginx.
  apt_repository:
    repo: "ppa:nginx/{{ nginx_ppa_version }}"
    state: present
    update_cache: true
    validate_certs: true
  register: nginx_ppa_added
  when: nginx_ppa_use

- name: Ensure nginx will reinstall if the PPA was just added.
  apt:
    name: nginx
    state: absent
  when: nginx_ppa_added.changed
