# Variables that can be used to configure this role

# User the FC backend will be installed under
fc_user: celery

# Where to install Python packages for the backend
fc_virtualenv: /opt/celery/venv

# Chaste backend configuration
chaste_repo: https://chaste.cs.ox.ac.uk/git/chaste.git
fc_repo: https://chaste.cs.ox.ac.uk/svn/chaste/projects/FunctionalCuration
chaste_root: "{{ user_meta[fc_user].home }}/eclipse/workspace/Chaste"
fc_project_name: FunctionalCuration
fc_root: "{{ chaste_root }}/projects/{{ fc_project_name }}"
chaste_fc_exe: "{{ fc_root }}/apps/src/FunctionalCuration"

chaste_version: 0ff3ad0a2d3bdba18b5e615f6b8d5d93ed1fc7db

# FC fitting prototype
fitting_prototype_repo: https://github.com/ModellingWebLab/chaste-project-fitting-pints.git
fitting_prototype_project_name: "AidanDaly"
fitting_prototype_root: "{{ chaste_root }}/projects/{{ fitting_prototype_project_name }}"
fitting_exe: "{{ fitting_prototype_root }}/cardiac.py"
