# Make sure we have our common Python tools installed

- name: Install Python 2.7 via apt
  apt:
    name: ["python2.7-dev", "python-pip", "python-virtualenv"]
    state: present
  become: true

- name: Install Python 3.8 via apt
  apt:
    name: ["python3.8-dev", "python3-pip", "python3.8-venv"]
    state: present
  become: true

- name: Install additional Python tools via apt
  apt:
    name: ["python-psycopg2", "virtualenv"]
    state: present
  become: true

# Set pip to versions known to work with Web Lab components
- name: Upgrade Python 2 system pip
  become: true
  pip:
    name: pip
    version: ">=20,<24.1"
    executable: pip2

- name: Upgrade Python 3 system pip
  become: true
  pip:
    name: pip
    version: ">=20,<24.1"
    executable: pip3

# Upgrade pyOpenSSL to avoid python-openssl breaking pip
- name: Upgrade Python 2 system pyOpenSSL
  become: true
  pip:
    name: pyOpenSSL
    version: ">=21"
    executable: pip2

- name: Upgrade Python 3 system pyOpenSSL
  become: true
  pip:
    name: pyOpenSSL
    version: ">=21"
    executable: pip3
