# Make sure we have our common Python tools installed

- name: Install Python
  apt:
    name: ['python3', 'python3-pip', 'python3-venv', 'python-pip', 'python-virtualenv', 'python-psycopg2']
    state: present
  become: yes

- name: Upgrade system pip
  become: yes
  pip:
    name: pip
    state: latest

- name: Upgrade pyOpenSSL to avoid python-openssl breaking pip
  become: yes
  pip:
    name: pyOpenSSL
    state: latest

- name: Install Python 3.7
  become: yes
  block:
    - name: Enable deadsnakes ppa
      apt_repository:
        repo: ppa:deadsnakes/ppa
    - name: Install Python 3.7
      apt:
        name: ['python3.7', 'python3.7-dev', 'python3.7-venv']
        state: present
