# Make sure we have our common Python tools installed

- name: Install Python
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python3
    - python3-pip
    - python3-venv
    - python-pip
    - python-virtualenv
  become: yes
