# Our specific tasks for configuring nginx for the backend web service
# Most is done by the imported geerlingguy.nginx role

# We also cheat and re-use the virtualenv created by the fc-backend role

- name: fc-web-service | Install virtualenv wrapper
  template:
    src: fc_runner.py.j2
    dest: '{{ fc_webservice_cgi_dir }}/fc_runner.py'
    owner: '{{ fc_webservice_user }}'
    group: '{{ fc_webservice_group }}'
    mode: 0755
  notify: restart fcgiwrap

- name: fc-web-service | Install fcgiwrap
  apt:
    name: fcgiwrap
    state: present

- name: fc-web-service | Configure nginx
  become: yes
  import_role:
    name: geerlingguy.nginx

- name: fc-web-service | Open port
  with_items: '{{ groups["webserver"] }}'
  ufw:
    proto: tcp
    to_port: '{{ fc_webservice_port }}'
    direction: in
    src: '{{ hostvars[item].ansible_default_ipv4.address }}'
    rule: allow
    state: enabled

- name: fc-web-service | Open localhost port
  ufw:
    proto: tcp
    to_port: '{{ fc_webservice_port }}'
    direction: in
    src: 127.0.0.1
    rule: allow
    state: enabled

- name: fc-web-service | Allow access from host
  ufw:
    proto: tcp
    to_port: '{{ fc_webservice_port }}'
    direction: in
    rule: allow
    state: enabled
  when: inventory == 'dev'
