# Our specific tasks for configuring nginx for the backend web service
# Most is done by the imported geerlingguy.nginx role

- name: fc-web-service | Install fcgiwrap
  apt:
    name: fcgiwrap
    state: present

- name: fc-web-service | Configure nginx
  import_role:
    name: geerlingguy.nginx

- name: fc-web-service | Open http port
  ufw:
    proto: tcp
    to_port: 80
    direction: in
    src: '{{ frontend_ip }}'
    rule: allow
    state: enabled
