# Tasks to clone the Web Lab ontology definitions and install in the appropriate locations

- name: Ensure folders exist with correct permissions
  become: true
  file:
    path: '{{ item }}'
    state: directory
    owner: '{{ onto_user }}'
    mode: 0755
  with_items:
    - '{{ onto_root }}'

- name: Checkout repository
  become: true
  become_user: '{{ onto_user }}'
  become_method: sudo
  git:
    clone: true
    dest: '{{ onto_root }}'
    repo: '{{ onto_repo }}'
    version: '{{ onto_branch }}'
    update: true
    force: true

- name: Copy ontology file to destination
  become: true
  copy:
    src: '{{ onto_rdf_xml }}'
    remote_src: true
    dest: '{{ onto_destination }}'
    force: true
    mode: 0644
