# Handlers for uWSGI

- name: start uwsgi
  become: true
  service:
    name: uwsgi
    state: started

- name: restart uwsgi
  become: true
  service:
    name: uwsgi
    state: restarted

- name: reload uwsgi
  become: true
  service:
    name: uwsgi
    state: reloaded

- name: restart rsyslog
  become: true
  service:
    name: rsyslog
    state: restarted
