# Variables applicable to the front-end web server

# TODO: Figure out which are different between dev/staging/production and how to represent this

# Where to obtain the code from

django_git_repo: https://github.com/ModellingWebLab/WebLab.git
django_git_branch: master

# Where to put the code etc on the server

django_user: weblab_django
django_dir: /opt/django

# Typically you won't need to edit the next section, only the main django_dir above
# At least some of these are needed by several roles, hence why they're given here

django_checkout: "{{ django_dir }}/WebLab"
django_app_path: "{{ django_checkout }}/weblab"
django_static_path: "{{ django_app_path }}/static"
django_data_path: "{{ django_dir }}/data"
django_staticfiles_path: "{{ django_data_path }}/staticfiles"
django_media_path: "{{ django_data_path }}/media"
django_entity_repos_path: "{{ django_data_path }}/repositories"
django_virtualenv: "{{ django_dir }}/venv"

# Initial superuser account info - should be passed on command line if desired,
# using -e 'django_superuser_email="..."' etc.

django_superuser_email: ""
django_superuser_full_name: ""
django_superuser_institution: ""

# Email addresses to use as admin contacts for Django

django_admin_emails:
  - ['Jonathan', 'j.p.cooper@ucl.ac.uk']
django_from_email: 'Cardiac Web Lab <chaste-admin@maillist.ox.ac.uk>'

# Access settings for the postgres DB used by Django

django_db_name: weblab
django_db_user: weblab
django_db_pass: '{{ vault_django_db_pass }}'

# The webserver hostname - by default figured out by Ansible
webserver_fqdn: "{{ ansible_fqdn }}"
webserver_ipv4: "{{ ansible_default_ipv4.address }}"

# nginx & uWSGI settings

nginx_user: www-data
nginx_group: www-data

uwsgi_app: weblab
uwsgi_socket_dir: /run/uwsgi
uwsgi_socket: "{{ uwsgi_socket_dir }}/{{ uwsgi_app }}.sock"

# How to send emails from the server

email_smtp_host: 'smtp.ox.ac.uk'
email_smtp_port: 25
email_smtp_user: ''
email_smtp_password: ''
email_use_tls: False
email_use_ssl: False

# Django secrets

django_secret_key: '{{ vault_django_secret_key }}'

# Google OAuth2 - see http://code.google.com/apis/accounts/docs/OAuth2.html#Registering
django_google_oauth_key: '{{ vault_django_google_oauth_key }}'
django_google_oauth_secret: '{{ vault_django_google_oauth_secret }}'

# GitHub - see https://github.com/settings/applications/new
django_github_key: '{{ vault_django_github_key }}'
django_github_secret: '{{ vault_django_github_secret }}'
