# Variables applicable to the front-end web server

# Where to obtain the code from

django_git_repo: https://github.com/ModellingWebLab/WebLab.git

# Where to put the code etc on the server

django_user: weblab_django
django_dir: /opt/django

# Typically you won't need to edit the next section, only the main django_dir above
# At least some of these are needed by several roles, hence why they're given here

django_checkout: "{{ django_dir }}/WebLab"
django_app_path: "{{ django_checkout }}/weblab"
django_static_path: "{{ django_app_path }}/static"
django_data_path: "{{ django_dir }}/data"
django_staticfiles_path: "{{ django_data_path }}/staticfiles"
django_media_path: "{{ django_data_path }}/media"
django_entity_repos_path: "{{ django_data_path }}/repositories"
django_experiments_path: "{{ django_data_path }}/experiments"
django_virtualenv: "{{ django_dir }}/venv"

# Initial superuser account info - should be passed on command line if desired,
# using -e 'django_superuser_email="..."' etc.

django_superuser_email: ""
django_superuser_full_name: ""
django_superuser_institution: ""

# Access settings for the postgres DB used by Django

django_db_name: weblab
django_db_user: weblab

# nginx & uWSGI settings

uwsgi_app: weblab
uwsgi_socket_dir: /run/uwsgi
uwsgi_socket: "{{ uwsgi_socket_dir }}/{{ uwsgi_app }}.sock"
